// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_todos.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookingTodo = `-- name: CreateBookingTodo :one
INSERT INTO booking_todos (trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, position, auto)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false)
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at
`

type CreateBookingTodoParams struct {
	TripID     uuid.UUID   `json:"trip_id"`
	Kind       string      `json:"kind"`
	TodoKey    string      `json:"todo_key"`
	Title      string      `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	Provider   *string     `json:"provider"`
	SearchUrl  *string     `json:"search_url"`
	DepartDate pgtype.Date `json:"depart_date"`
	ReturnDate pgtype.Date `json:"return_date"`
	Position   int32       `json:"position"`
}

func (q *Queries) CreateBookingTodo(ctx context.Context, arg CreateBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, createBookingTodo,
		arg.TripID,
		arg.Kind,
		arg.TodoKey,
		arg.Title,
		arg.Subtitle,
		arg.Provider,
		arg.SearchUrl,
		arg.DepartDate,
		arg.ReturnDate,
		arg.Position,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookingTodo = `-- name: DeleteBookingTodo :execrows
DELETE FROM booking_todos WHERE id = $1 AND trip_id = $2
`

type DeleteBookingTodoParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteBookingTodo(ctx context.Context, arg DeleteBookingTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookingTodo, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleAutoBookingTodos = `-- name: DeleteStaleAutoBookingTodos :execrows
DELETE FROM booking_todos
WHERE trip_id = $1 AND auto = true AND todo_key <> ALL($2::text[])
`

type DeleteStaleAutoBookingTodosParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Keys   []string  `json:"keys"`
}

func (q *Queries) DeleteStaleAutoBookingTodos(ctx context.Context, arg DeleteStaleAutoBookingTodosParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAutoBookingTodos, arg.TripID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBookingTodosByTrip = `-- name: ListBookingTodosByTrip :many
SELECT id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at FROM booking_todos WHERE trip_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBookingTodosByTrip(ctx context.Context, tripID uuid.UUID) ([]BookingTodo, error) {
	rows, err := q.db.Query(ctx, listBookingTodosByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingTodo
	for rows.Next() {
		var i BookingTodo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Kind,
			&i.TodoKey,
			&i.Title,
			&i.Subtitle,
			&i.Provider,
			&i.SearchUrl,
			&i.DepartDate,
			&i.ReturnDate,
			&i.Booked,
			&i.Auto,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingTodoBooked = `-- name: SetBookingTodoBooked :one
UPDATE booking_todos SET booked = $3 WHERE id = $1 AND trip_id = $2 RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at
`

type SetBookingTodoBookedParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
	Booked bool      `json:"booked"`
}

func (q *Queries) SetBookingTodoBooked(ctx context.Context, arg SetBookingTodoBookedParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, setBookingTodoBooked, arg.ID, arg.TripID, arg.Booked)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBookingTodo = `-- name: UpsertBookingTodo :one
INSERT INTO booking_todos (trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, position, auto)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true)
ON CONFLICT (trip_id, todo_key) DO UPDATE SET
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    provider = EXCLUDED.provider,
    search_url = EXCLUDED.search_url,
    depart_date = EXCLUDED.depart_date,
    return_date = EXCLUDED.return_date,
    position = EXCLUDED.position
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at
`

type UpsertBookingTodoParams struct {
	TripID     uuid.UUID   `json:"trip_id"`
	Kind       string      `json:"kind"`
	TodoKey    string      `json:"todo_key"`
	Title      string      `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	Provider   *string     `json:"provider"`
	SearchUrl  *string     `json:"search_url"`
	DepartDate pgtype.Date `json:"depart_date"`
	ReturnDate pgtype.Date `json:"return_date"`
	Position   int32       `json:"position"`
}

func (q *Queries) UpsertBookingTodo(ctx context.Context, arg UpsertBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, upsertBookingTodo,
		arg.TripID,
		arg.Kind,
		arg.TodoKey,
		arg.Title,
		arg.Subtitle,
		arg.Provider,
		arg.SearchUrl,
		arg.DepartDate,
		arg.ReturnDate,
		arg.Position,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
