// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Accommodation struct {
	ID        uuid.UUID   `json:"id"`
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	Address   *string     `json:"address"`
	Latitude  *float64    `json:"latitude"`
	Longitude *float64    `json:"longitude"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ItineraryItem struct {
	ID        uuid.UUID `json:"id"`
	TripID    uuid.UUID `json:"trip_id"`
	Position  int32     `json:"position"`
	Name      string    `json:"name"`
	PlaceID   *string   `json:"place_id"`
	Address   *string   `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	CreatedAt time.Time `json:"created_at"`
	Category  *string   `json:"category"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TravelerPreference struct {
	UserID    uuid.UUID `json:"user_id"`
	Budget    *string   `json:"budget"`
	Pace      *string   `json:"pace"`
	Interests []string  `json:"interests"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Trip struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    string      `json:"status"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  *string   `json:"display_name"`
}
