// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Accommodation struct {
	ID        uuid.UUID   `json:"id"`
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	Address   *string     `json:"address"`
	Latitude  *float64    `json:"latitude"`
	Longitude *float64    `json:"longitude"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type BookingTodo struct {
	ID         uuid.UUID   `json:"id"`
	TripID     uuid.UUID   `json:"trip_id"`
	Kind       string      `json:"kind"`
	TodoKey    string      `json:"todo_key"`
	Title      string      `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	Provider   *string     `json:"provider"`
	SearchUrl  *string     `json:"search_url"`
	DepartDate pgtype.Date `json:"depart_date"`
	ReturnDate pgtype.Date `json:"return_date"`
	Booked     bool        `json:"booked"`
	Auto       bool        `json:"auto"`
	Position   int32       `json:"position"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type ItineraryItem struct {
	ID          uuid.UUID `json:"id"`
	TripID      uuid.UUID `json:"trip_id"`
	Position    int32     `json:"position"`
	Name        string    `json:"name"`
	PlaceID     *string   `json:"place_id"`
	Address     *string   `json:"address"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
	CreatedAt   time.Time `json:"created_at"`
	Category    *string   `json:"category"`
	TimeOfDay   *string   `json:"time_of_day"`
	City        *string   `json:"city"`
	DayTripFrom *string   `json:"day_trip_from"`
	Day         *int32    `json:"day"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TravelerPreference struct {
	UserID      uuid.UUID `json:"user_id"`
	Budget      *string   `json:"budget"`
	Pace        *string   `json:"pace"`
	Interests   []string  `json:"interests"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	HomeAirport *string   `json:"home_airport"`
}

type Trip struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    string      `json:"status"`
	ChatID    *string     `json:"chat_id"`
	Summary   *string     `json:"summary"`
}

type TripSegment struct {
	ID          uuid.UUID   `json:"id"`
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  *string   `json:"display_name"`
	IsAdmin      bool      `json:"is_admin"`
}
