// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPreferences = `-- name: GetPreferences :one
SELECT user_id, budget, pace, interests, created_at, updated_at, home_airport FROM traveler_preferences WHERE user_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) (TravelerPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i TravelerPreference
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.Pace,
		&i.Interests,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeAirport,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO traveler_preferences (user_id, budget, pace, interests, home_airport)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, '{}'::text[]),
    $5
)
ON CONFLICT (user_id) DO UPDATE SET
    budget       = COALESCE($2, traveler_preferences.budget),
    pace         = COALESCE($3, traveler_preferences.pace),
    interests    = COALESCE($4, traveler_preferences.interests),
    home_airport = COALESCE($5, traveler_preferences.home_airport)
RETURNING user_id, budget, pace, interests, created_at, updated_at, home_airport
`

type UpsertPreferencesParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Budget      *string     `json:"budget"`
	Pace        *string     `json:"pace"`
	Interests   interface{} `json:"interests"`
	HomeAirport *string     `json:"home_airport"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (TravelerPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.UserID,
		arg.Budget,
		arg.Pace,
		arg.Interests,
		arg.HomeAirport,
	)
	var i TravelerPreference
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.Pace,
		&i.Interests,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeAirport,
	)
	return i, err
}
