// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPreferences = `-- name: GetPreferences :one
SELECT user_id, budget, pace, interests, created_at, updated_at, home_airport, profile_notes, work_style, fitness_routine, outdoor_intensity, companions, baggage, gender FROM traveler_preferences WHERE user_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) (TravelerPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i TravelerPreference
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.Pace,
		&i.Interests,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeAirport,
		&i.ProfileNotes,
		&i.WorkStyle,
		&i.FitnessRoutine,
		&i.OutdoorIntensity,
		&i.Companions,
		&i.Baggage,
		&i.Gender,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO traveler_preferences (user_id, budget, pace, interests, home_airport, profile_notes, work_style, fitness_routine, outdoor_intensity, companions, baggage, gender)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, '{}'::text[]),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (user_id) DO UPDATE SET
    budget            = COALESCE($2, traveler_preferences.budget),
    pace              = COALESCE($3, traveler_preferences.pace),
    interests         = COALESCE($4, traveler_preferences.interests),
    -- Removing a home airport needs a signal COALESCE cannot carry: NULL means
    -- "omitted, keep what's there", so without this flag the column could only
    -- ever be set or replaced, never emptied. Writes a real NULL rather than an
    -- empty-string sentinel, so "no home airport" has exactly one representation.
    home_airport      = CASE
        WHEN $13::boolean THEN NULL
        ELSE COALESCE($5, traveler_preferences.home_airport)
    END,
    profile_notes     = COALESCE($6, traveler_preferences.profile_notes),
    work_style        = COALESCE($7, traveler_preferences.work_style),
    fitness_routine   = COALESCE($8, traveler_preferences.fitness_routine),
    outdoor_intensity = COALESCE($9, traveler_preferences.outdoor_intensity),
    companions        = COALESCE($10, traveler_preferences.companions),
    baggage           = COALESCE($11, traveler_preferences.baggage),
    -- Clearable like home_airport (and unlike the other enum fields): a
    -- stored gender the traveler cannot remove is not acceptable, so ""
    -- on the PUT becomes a real NULL here.
    gender            = CASE
        WHEN $14::boolean THEN NULL
        ELSE COALESCE($12, traveler_preferences.gender)
    END
RETURNING user_id, budget, pace, interests, created_at, updated_at, home_airport, profile_notes, work_style, fitness_routine, outdoor_intensity, companions, baggage, gender
`

type UpsertPreferencesParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	Budget           *string     `json:"budget"`
	Pace             *string     `json:"pace"`
	Interests        interface{} `json:"interests"`
	HomeAirport      *string     `json:"home_airport"`
	ProfileNotes     *string     `json:"profile_notes"`
	WorkStyle        *string     `json:"work_style"`
	FitnessRoutine   *string     `json:"fitness_routine"`
	OutdoorIntensity *string     `json:"outdoor_intensity"`
	Companions       *string     `json:"companions"`
	Baggage          *string     `json:"baggage"`
	Gender           *string     `json:"gender"`
	ClearHomeAirport bool        `json:"clear_home_airport"`
	ClearGender      bool        `json:"clear_gender"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (TravelerPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.UserID,
		arg.Budget,
		arg.Pace,
		arg.Interests,
		arg.HomeAirport,
		arg.ProfileNotes,
		arg.WorkStyle,
		arg.FitnessRoutine,
		arg.OutdoorIntensity,
		arg.Companions,
		arg.Baggage,
		arg.Gender,
		arg.ClearHomeAirport,
		arg.ClearGender,
	)
	var i TravelerPreference
	err := row.Scan(
		&i.UserID,
		&i.Budget,
		&i.Pace,
		&i.Interests,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeAirport,
		&i.ProfileNotes,
		&i.WorkStyle,
		&i.FitnessRoutine,
		&i.OutdoorIntensity,
		&i.Companions,
		&i.Baggage,
		&i.Gender,
	)
	return i, err
}
