// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO trip_segments (trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at
`

type CreateSegmentParams struct {
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (TripSegment, error) {
	row := q.db.QueryRow(ctx, createSegment,
		arg.TripID,
		arg.Mode,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.ArriveDate,
		arg.Provider,
		arg.Url,
		arg.PriceNote,
		arg.Notes,
	)
	var i TripSegment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Mode,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ArriveDate,
		&i.Provider,
		&i.Url,
		&i.PriceNote,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :execrows
DELETE FROM trip_segments WHERE id = $1 AND trip_id = $2
`

type DeleteSegmentParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSegment, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSegmentsByTrip = `-- name: ListSegmentsByTrip :many
SELECT id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at FROM trip_segments WHERE trip_id = $1 ORDER BY depart_date ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListSegmentsByTrip(ctx context.Context, tripID uuid.UUID) ([]TripSegment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripSegment
	for rows.Next() {
		var i TripSegment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Mode,
			&i.Origin,
			&i.Destination,
			&i.DepartDate,
			&i.ArriveDate,
			&i.Provider,
			&i.Url,
			&i.PriceNote,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
