// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, position, name, place_id, address, latitude, longitude, category)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category
`

type CreateItineraryItemParams struct {
	TripID    uuid.UUID `json:"trip_id"`
	Position  int32     `json:"position"`
	Name      string    `json:"name"`
	PlaceID   *string   `json:"place_id"`
	Address   *string   `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	Category  *string   `json:"category"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.Position,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, status, chat_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id
`

type CreateTripParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Status string    `json:"status"`
	ChatID *string   `json:"chat_id"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.ChatID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips WHERE id = $1 AND user_id = $2
`

type DeleteTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItineraryItemsByTrip = `-- name: GetItineraryItemsByTrip :many
SELECT id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category FROM itinerary_items WHERE trip_id = $1 ORDER BY position ASC
`

func (q *Queries) GetItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, getItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryItem
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Position,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripByIDAndOwner = `-- name: GetTripByIDAndOwner :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDAndOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByIDAndOwner(ctx context.Context, arg GetTripByIDAndOwnerParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByIDAndOwner, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
	)
	return i, err
}

const listLatestTripsByOwner = `-- name: ListLatestTripsByOwner :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, version_count FROM (
  SELECT DISTINCT ON (COALESCE(chat_id, id::text))
         id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id,
         count(*) OVER (PARTITION BY COALESCE(chat_id, id::text)) AS version_count
  FROM trips WHERE user_id = $1
  ORDER BY COALESCE(chat_id, id::text), created_at DESC
) latest ORDER BY created_at DESC
`

type ListLatestTripsByOwnerRow struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	Title        string      `json:"title"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	Status       string      `json:"status"`
	ChatID       *string     `json:"chat_id"`
	VersionCount int64       `json:"version_count"`
}

// One row per chat group (latest version), with how many versions exist.
// Legacy trips with NULL chat_id stand alone (grouped by their own id).
func (q *Queries) ListLatestTripsByOwner(ctx context.Context, userID uuid.UUID) ([]ListLatestTripsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLatestTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestTripsByOwnerRow
	for rows.Next() {
		var i ListLatestTripsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
			&i.VersionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripVersionsByChat = `-- name: ListTripVersionsByChat :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id FROM trips WHERE user_id = $1 AND chat_id = $2 ORDER BY created_at DESC
`

type ListTripVersionsByChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

func (q *Queries) ListTripVersionsByChat(ctx context.Context, arg ListTripVersionsByChatParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripVersionsByChat, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByOwner = `-- name: ListTripsByOwner :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id FROM trips WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTripsByOwner(ctx context.Context, userID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title      = COALESCE($1, title),
    start_date = COALESCE($2, start_date),
    end_date   = COALESCE($3, end_date),
    status     = COALESCE($4, status),
    chat_id    = COALESCE($5, chat_id)
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id
`

type UpdateTripParams struct {
	Title     *string     `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    *string     `json:"status"`
	ChatID    *string     `json:"chat_id"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ChatID,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
	)
	return i, err
}
