// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, position, name, place_id, address, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at
`

type CreateItineraryItemParams struct {
	TripID    uuid.UUID `json:"trip_id"`
	Position  int32     `json:"position"`
	Name      string    `json:"name"`
	PlaceID   *string   `json:"place_id"`
	Address   *string   `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.Position,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, status)
VALUES ($1, $2, $3)
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status
`

type CreateTripParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Status string    `json:"status"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip, arg.UserID, arg.Title, arg.Status)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips WHERE id = $1 AND user_id = $2
`

type DeleteTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItineraryItemsByTrip = `-- name: GetItineraryItemsByTrip :many
SELECT id, trip_id, position, name, place_id, address, latitude, longitude, created_at FROM itinerary_items WHERE trip_id = $1 ORDER BY position ASC
`

func (q *Queries) GetItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, getItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryItem
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Position,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripByIDAndOwner = `-- name: GetTripByIDAndOwner :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDAndOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByIDAndOwner(ctx context.Context, arg GetTripByIDAndOwnerParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByIDAndOwner, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const listTripsByOwner = `-- name: ListTripsByOwner :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status FROM trips WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTripsByOwner(ctx context.Context, userID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title      = COALESCE($1, title),
    start_date = COALESCE($2, start_date),
    end_date   = COALESCE($3, end_date),
    status     = COALESCE($4, status)
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status
`

type UpdateTripParams struct {
	Title     *string     `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    *string     `json:"status"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}
